kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.15-alpine
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go test -timeout 10s -v .
      - go build
